In [12]:
import pandas as pd

In [13]:
df_claim_lines=pd.read_csv(r'C:\Users\User\Desktop\Classroom\datas_csv\claim_lines_merged.csv')

In [14]:
df_claim_lines.head(10)

,line_id,claim_number,service_date,procedure_code,units,rate,line_amount
0,LN000153930,CL00052122,2024-06-19 08:12:14.718039,CPT31290,2,2337.75,4675.50
1,LN000530073,CL00058807,2025-07-13 04:57:45.718039,CPT52344,7,8743.91,61207.37
2,LN000671612,__ORPHAN__,2024-06-17 17:04:04.499393,CPT15125,-4,MISSING,-316.30
3,LN000759650,__ORPHAN__,2024-07-07 02:14:32.499393,CPT43151,-1,MISSING,-670.25
4,LN000329031,CL00192957,2024-03-25 06:41:15.718039,CPT45895,7,13509.23,94564.61
5,LN000121355,CL00001212,2025-05-13 03:25:53.718039,CPT90735,5,8029.74,40148.70
6,LN000514569,CL00050634,2024-11-08 13:21:44.718039,CPT70710,1,8485.05,8485.05
7,LN000056903,CL00073715,2023-08-08 18:35:55.718039,CPT92316,3,15304.08,45912.24
8,LN000032895,CL00005237,2024-08-31 16:04:13.718039,CPT35032,7,872.0,6104.00
9,LN000185018,CL00066903,2024-08-20 04:12:44.718039,CPT35010,1,10675.37,10675.37

In [15]:
len(df_claim_lines)

760000

In [16]:
count_orphans = len(df_claim_lines[df_claim_lines["claim_number"] == "__ORPHAN__"])

print(f"Number of orphan claim lines: {count_orphans}")

Number of orphan claim lines: 110000

In [17]:
duplicates_column_df = df_claim_lines[df_claim_lines.duplicated(subset=["claim_number", "line_id"])]

duplicates_column_count = len(duplicates_column_df)
print(f"Number of duplicate claim_number and line_id rows: {duplicates_column_count}")

Number of duplicate claim_number and line_id rows: 542

In [18]:
clean_claim_lines_df = df_claim_lines[df_claim_lines["claim_number"] != "__ORPHAN__"]

In [19]:
clean_claim_lines_df.head(10)

,line_id,claim_number,service_date,procedure_code,units,rate,line_amount
0,LN000153930,CL00052122,2024-06-19 08:12:14.718039,CPT31290,2,2337.75,4675.50
1,LN000530073,CL00058807,2025-07-13 04:57:45.718039,CPT52344,7,8743.91,61207.37
4,LN000329031,CL00192957,2024-03-25 06:41:15.718039,CPT45895,7,13509.23,94564.61
5,LN000121355,CL00001212,2025-05-13 03:25:53.718039,CPT90735,5,8029.74,40148.70
6,LN000514569,CL00050634,2024-11-08 13:21:44.718039,CPT70710,1,8485.05,8485.05
7,LN000056903,CL00073715,2023-08-08 18:35:55.718039,CPT92316,3,15304.08,45912.24
8,LN000032895,CL00005237,2024-08-31 16:04:13.718039,CPT35032,7,872.0,6104.00
9,LN000185018,CL00066903,2024-08-20 04:12:44.718039,CPT35010,1,10675.37,10675.37
10,LN000326577,CL00027021,2025-08-07 19:33:11.718039,CPT57501,9,17521.55,157693.95
11,LN000608525,CL00133010,2024-11-21 19:10:17.718039,CPT88863,7,14028.38,98198.66

In [22]:
clean_claim_lines_df = clean_claim_lines_df.drop_duplicates(subset=["line_id", "claim_number"])

In [21]:
clean_claim_lines_df.to_csv("claim_lines_cleaned.csv", index=False)